#Gradle
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx1g" -XX:+UseParallelGC
org.gradle.caching=false
org.gradle.configuration-cache=false
org.gradle.parallel=true

#Kotlin
kotlin.code.style=official
kotlin.native.ignoreDisabledTargets=true
kotlin.incremental.native=false

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true
android.enableJetifier=false

#Moko
moko.resources.disableStaticFrameworkWarning=false

#BuildKonfig
buildkonfig.flavor=mock