#Gradle
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4g" -XX:+UseParallelGC
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=true

#Kotlin
kotlin.code.style=official
kotlin.native.ignoreDisabledTargets=true
kotlin.incremental.native=false

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true

#Moko
moko.resources.disableStaticFrameworkWarning=true

#BuildKonfig
buildkonfig.flavor=any